{% set version = "4.66.2" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 6cd52cdf0fef0e0f543299cfc96fec90d7b8a7e88745f411ec33eb44d5ed3531

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - tqdm = tqdm.cli:main
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.4
    - setuptools
    - toml
    - wheel
  run:
    - python
    - colorama  # [win]
  run_constrained:
    - ipywidgets >=6

test:
  requires:
    - dask-core
    - pandas
    - numpy
    - pip
    - pytest >=6
    - pytest-timeout
    - pytest-xdist
    - pytest-asyncio
    - rich
    - ripgrep
  source_files:
    - tests
    - pyproject.toml
  imports:
    - tqdm
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg {{ version }}
    - pytest -k "not tests_perf"

about:
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  description: A Fast, Extensible Progress Bar for Python and CLI
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
