{% set name = "tqdm" %}
{% set version = "4.15.0" %}
{% set compress_type = "tar.gz" %}
{% set build_num = "0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "6ec1dc74efacf2cda936b4a6cf4082ce224c76763bdec9f17e437c8cfcaa9953" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - tqdm=tqdm._main:main

  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://github.com/tqdm/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'A Fast, Extensible Progress Meter'
  dev_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - lrq3000
    - pmlandwehr
    - ericdill
