{% set version = "4.53.0" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 3d3f1470d26642e88bd3f73353cb6ff4c51ef7d5d7efef763238f4bc1f7e4e81

build:
  noarch: python
  entry_points:
    - tqdm = tqdm.cli:main
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=2.7

test:
  requires:
    - pip

  imports:
    - tqdm

  commands:
    - pip check
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_family: MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - ericdill
