{% set version = "4.7.6" %}

package:
  name: tqdm
  version: {{ version }}

source:
  fn: tqdm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: a0b615a402003bac24a065e88fb54832a974d7bc5412fe7b348e0d1fe80f00fd

build:
  entry_points:
    - tqdm=tqdm._main:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://github.com/tqdm/tqdm
  license: Mozilla Public License 2.0 (MPL 2.0) or MIT License
  summary: 'A Fast, Extensible Progress Meter'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ericdill
