{% set version = "4.43.0" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: f35fb121bafa030bd94e74fcfd44f3c2830039a2ddef7fc87ef1c2d205237b24

build:
  noarch: python
  entry_points:
    - tqdm = tqdm._main:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'A Fast, Extensible Progress Meter'
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - ericdill
