{% set version = "4.52.0" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 18d6a615aedd09ec8456d9524489dab330af4bd5c2a14a76eb3f9a0e14471afe

build:
  noarch: python
  entry_points:
    - tqdm = tqdm.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - ericdill
