{% set version = "4.48.0" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 6baa75a88582b1db6d34ce4690da5501d2a1cb65c34664840a456b2c9f794d29

build:
  noarch: python
  entry_points:
    - tqdm = tqdm.cli:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - ericdill
