{% set version = "4.63.1" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: 4230a49119a416c88cc47d0d2d32d5d90f1a282d5e497d49801950704e49863d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tqdm = tqdm.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.4
    - setuptools >=42
    - toml
    - wheel
  run:
    - python >=2.7
    - colorama

test:
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-asyncio
  source_files:
    - tests
    - setup.cfg
    - pyproject.toml
  imports:
    - tqdm
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf"

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm#tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr