{% set version = "4.23.0" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: fe3d218d5b61993d415aa2a9db6dd64c0e4cefb90164ebb197ef3b1d99f531dc

build:
  entry_points:
    - tqdm = tqdm._main:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'A Fast, Extensible Progress Meter'
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - lrq3000
    - pmlandwehr
    - ericdill
