{% set version = "4.40.2" %}

package:
  name: tqdm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tqdm/tqdm-{{ version }}.tar.gz
  sha256: f0ab01cf3ae5673d18f918700c0165e5fad0f26b5ebe4b34f62ead92686b5340

build:
  noarch: python
  entry_points:
    - tqdm = tqdm._main:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://pypi.python.org/pypi/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'A Fast, Extensible Progress Meter'
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://github.com/tqdm/tqdm

extra:
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
    - ericdill
