{% set name = "tqdm" %}
{% set version = "4.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bab05f8bb6efd2702ab6c532e5e6a758a66c0d2f443e09784b73e4066e6b3a37

build:
  entry_points:
    - tqdm=tqdm._main:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - tqdm

  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://github.com/tqdm/tqdm
  license: Mozilla Public License 2.0 (MPL 2.0) or MIT License
  summary: 'A Fast, Extensible Progress Meter'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ericdill
