travis:
  secure:
    BINSTAR_TOKEN: HeoRAW99DaGCu8/Xw7vEBCMHkqLwxX24ZB6zRQ3GPK/4ZLPmZWKlm0MhaD7pYhWpdEsHPpuHaY2bDavMsfH0zWO4Oc7Aj5kke6TC8u7t1uHDYgARvUG7GkZbRoHbhj7sZaJpobdUMaP/S9epPWo4+YR/i/IrjIwQIfhya6dNvsObVZTuDxmxi4JWlag7n4jGsLGyb2pEhffsK8B3CDwhKJWqcdP8Ug/TRQRZMtT9i6lEnuuBdonAfGyovE0bUqFyYEw3alFL/FacrTz5crLnySHF7lRTrqiUUOaFeSW9Kkdgv6HvqVcLjRbnVEYdwfPeMjy65NuHaR0tsVvD1JO8NZdZ1Vit75pIndtL0m9fTyP8rGIug3Dbx+pBZw+5vB1IPh89CHuptsWJNl3q5w2aflMq1gT02z+wRCVvFR/rltAv2La8TM+SuDtPxOBwo2CdAVAZphHVDf6tn+2TejE6dKhhjJUFX+j3lCpjU2+lpss8BuXFHbeWe4veOrTR3AkiGOZ2tmA4rKALnl0/WPGi6eKOAv3rDfRL+RGr2l1UBQu8zyHrIZqKVu9vt51TdY2S61EaXyvTizkPfaIQcK854FkMlxQREyBJdmoSa83BeuD7RWw5QsvlVE3CFE8gSD33A1BrTSjrGUnnAd0l5kxr7XNcqXFNawogV4llbB5zfFw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
