travis:
  secure:
    BINSTAR_TOKEN: HzJBGGAJNQRAvc/Hw2iuS47f7bUpizfDz9ROyPCKOF4fFvrXp7KnpdW/C4/ImXxGXtd3mRfweBP9fieXp0I1dnrmQBvscL2iSrY9sFoOOyeTh5ccRDocMPdm/jvC56xM0TmkMZlD3/0drsf5iPt4o6lsL2AKHHEXj2eaTFTngvg57aC5ESgPx5Kn8jaoiXuEpcXJeI+O7VBncEs+TVQY1EeCCkaraxvasiMkI8cJPRatBYVNdxdYZi4r6h8Ham5ApiYGtej99pqSiwdqs2MWn2zqekHPDVug/LWxojew0wrrwqgjmk5tHQaF3j/1uTTdKa2SI97qiyHI6NTKKkts3k2Xxs4tf76EAItYQnYasgyYQ+PfB7ukJuQ9+dRO8eE5Rg7epTU8Dg12Zzlm3zjZyBYBh8GZR9XE92CbT0EGNGRrNIjd3x4YHmIC/g6Ul6i0MKIodggofLf/YzAZT13AJpXsUVwwa2OUX4YWJDyQLj08PoJZiMP0i8DOJ+nuBWeqxDg3PNvisdZo+dR+qkEZ56sAEAgNwgsqHnWyRu1RPPme28qeoJ+qN3H7tMrbnnHyPvJNrsy7AFCrrXpPem26RNp8GrDKgiSLkmiFj3vV4DuffX6M02hSInowfSdddl5+FIHI7QRd4CONCAOqOeQAFBdtXCEiGIafSNfK/Vz3wcM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
